### ISSUE TITLE
cant install on heroku with the one click option

### ISSUE THREAD

**Issue by ugokingsley** [MicroPyramid/django-simple-forum#23]
cant install on heroku with the one click option 

ownloading psycopg2-2.6.1.tar.gz (371kB)
           Complete output from command python setup.py egg_info:
           running egg_info
           creating pip-egg-info/psycopg2.egg-info
           writing pip-egg-info/psycopg2.egg-info/PKG-INFO
           writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt
           writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
           writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'
           Error: could not determine PostgreSQL version from '10.1'
           
           ----------------------------------------
       Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-k798itbp/psycopg2/
 !     Push rejected, failed to compile Python app.
 !     Push failed

**Comment by ntbrown** [comment]
I created a pull request for this. This is a known bug with psycopg2 2.6. It is fixed in 2.7. So until (if) the pull request is merged you can simply update the requirements in sandbox/requirements.txt

**Comment by ashwin31** [comment]
@ugokingsley and @ntbrown the relevant pull request is merged.
